dbpath: C:/neo4j/db/main.db

server:
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091
  registerDefaultExceptionMappers: true  

swagger:
  resourcePackage: am.developer.resources